{{- if .Args.Tags -}}
// +build {{ .Args.Tags }}

{{ end -}}
// Package {{ .Args.Package }} contains the types for schema '{{ schema .Args.Schema }}'.
package {{ .Args.Package }}

// Code generated by xo.  DO NOT EDIT.
{{ range .Templates -}}
   {{ .Buf }}
{{ end -}}
