{{- if not .Args.SingleFile -}}
{{- if .Args.Tags -}}
// +build {{ .Args.Tags }}

{{ end -}}
// Package {{ .Args.Package }} contains the types for schema '{{ schema .Args.Schema }}'.
package {{ .Args.Package }}

// Code generated by xo.  DO NOT EDIT.

{{ end -}}

{{- if .Dots.enum -}}
	{{- range .Dots.enum -}}
		{{ template "enum" . }}
	{{ end -}}
{{- end -}}

{{- if .Dots.proc -}}
	{{- range .Dots.proc -}}
		{{ template "proc" . }}
	{{ end -}}
{{- end -}}

{{- if .Dots.type -}}
	{{- range .Dots.type -}}
		{{ template "type" . }}
	{{ end -}}
{{- end -}}

{{- if .Dots.foreignkey -}}
	{{- range .Dots.foreignkey -}}
		{{ template "foreignkey" . }}
	{{ end -}}
{{- end -}}

{{- if .Dots.index -}}
	{{- range .Dots.index -}}
		{{ template "index" . }}
	{{ end -}}
{{- end -}}

{{- if .Dots.querytype -}}
	{{- range .Dots.querytype -}}
		{{ template "querytype" . }}
	{{ end -}}
{{- end -}}

{{- if .Dots.query -}}
	{{- range .Dots.query -}}
		{{ template "query" . }}
	{{- end -}}
{{- end }}