{{- if not .Args.SingleFile -}}
{{- if .Args.Tags -}}
// +build {{ .Args.Tags }}

{{ end -}}
// Package {{ .Args.Package }} contains the types for schema '{{ schema .Args.Schema }}'.
package {{ .Args.Package }}

// Code generated by xo.  DO NOT EDIT.

{{ end -}}

{{- if .Dots.enum }}{{- range .Dots.enum }}
{{ template "enum" . }}
{{ end }} {{- end -}}

{{- if .Dots.proc }}{{- range .Dots.proc }}
{{ template "proc" .Dots.proc }}
{{ end }} {{- end -}}

{{- if .Dots.type }}{{- range .Dots.type }}
{{ template "type" .Dots.type }}
{{ end }} {{- end -}}

{{- if .Dots.foreignkey }}{{- range .Dots.foreignkey }}
{{ template "foreignkey" .Dots.foreignkey }}
{{ end }} {{- end -}}

{{- if .Dots.index }}{{- range .Dots.index }}
{{ template "index" .Dots.index }}
{{ end }} {{- end -}}

{{- if .Dots.querytype }}{{- range .Dots.querytype }}
{{ template "querytype" .Dots.querytype }}
{{ end }} {{- end -}}

{{- if .Dots.query }}{{- range .Dots.query }}
{{ template "query" .Dots.query }}
{{ end }} {{- end -}}