{{ if not .Args.SingleFile }}
{{ if .Args.Tags }}
// +build {{ .Args.Tags }}

{{ end }}
// Package {{ .Args.Package }} contains the types for schema '{{ schema .Args.Schema }}'.
package {{ .Args.Package }}

// Code generated by xo.  DO NOT EDIT.
{{ end }}

{{ template "enum" .Dots.enum }}

{{ template "proc" .Dots.proc }}

{{ template "type" .Dots.type }}

{{ template "foreignkey" .Dots.foreignkey }}

{{ template "index" .Dots.index }}

{{ template "querytype" .Dots.querytype }}

{{ template "query" .Dots.query }}
